### ISSUE TITLE
Error with latest SmartBuff and retail client

### ISSUE THREAD

**Issue by MyTechnoHunter** [Softrix/SmartBuff-Retail#23]
1x SmartBuff/SmartBuff.lua:359: attempt to index field '?' (a nil value)
[string "@SmartBuff/SmartBuff.lua"]:359: in function <SmartBuff/SmartBuff.lua:358>
[string "@SmartBuff/SmartBuff.lua"]:4560: in function <SMARTBUFF_BuffOrderReset>
[string "@SmartBuff/SmartBuff.lua"]:3135: in function <SMARTBUFF_Options_Init>
[string "@SmartBuff/SmartBuff.lua"]:531: in function <SMARTBUFF_OnEvent>
[string "@SmartBuff/SmartBuff.lua"]:720: in function <SMARTBUFF_OnUpdate>
[string "*SmartBuff.xml:41_OnUpdate"]:1: in function <[string "*SmartBuff.xml:41_OnUpdate"]:1>

Locals:
reset = true
(*temporary) = nil
(*temporary) = 2
(*temporary) = 2
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
B = <table> {
 1 = <table> {
 }
}
CS = <function> defined @SmartBuff/SmartBuff.lua:291
cBuffIndex = <table> {
}
cBuffs = <table> {
}

**Comment by speedwaystar** [comment]
does that happen (only) when you do a full reset? the fix atm is to reloadui, which is annoying but works.

**Comment by Softrix** [comment]
I can confirm this is an issue because it also existed in the build ive been working on for Wrath of the Lich King using the retail codebase.  However, the problem lies with the B table not being initialised correctly and I still need to trace it back to where and why.  

However, a quick fix for me until i get my lazt butt onto gear and trace it back was to add the checks in stages (not ideal but it stablised it for now).

In the function called **InitBuffOrder(reset)** at the top, I changed it to:

`
local function InitBuffOrder(reset)
  if not B then B = {} end
  if not B[CS()] then B[CS()] = {} end
  if not B[CS()].Order then B[CS()].Order = {} end
  local b;
  local i;
  local ord = B[CS()].Order;
  
  `

**Comment by speedwaystar** [comment]
to be fair that's a perfectly reasonable solution. I'll add it to the main
branch.

**Comment by MyTechnoHunter** [comment]
Ty kindly
